name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check --workspace --verbose --all-targets --all-features
    - name: Build
      run: cargo build --workspace --verbose --all-targets
    - name: Run tests
      run: cargo test --workspace --verbose --all-targets
