name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libsdl
      run: sudo apt-get update && sudo apt-get -y install libsdl2-dev

    - name: Build core, no features
      run: cargo build -p retrofire-core --verbose --all-targets --no-default-features
    - name: Build core, micromath
      run: cargo build -p retrofire-core --verbose --all-targets --no-default-features --features "mm"
    - name: Build core, libm
      run: cargo build -p retrofire-core --verbose --all-targets --no-default-features --features "libm"

    - name: Build workspace, std
      run: cargo build --workspace --verbose --all-targets --features "std"
    - name: Run tests, std
      run: cargo test --workspace --verbose --features "std"

